CommonMoudle/Areas/CitySelect/Models/CitySelectHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using NLog;
using com.telexpress.Data.DA;
using System.Data.SqlClient;

namespace CommonMoudle.Areas.CitySelect.Models
{
    public class CitySelectHelper
    {
        private static String sqlXmlFileName = "SQLXML\\CitySelect.xml";//SQL指令路徑
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();//使用NLog功能

        /// <summary>
        /// 初始化城市列表
        /// </summary>
        public static List<CityModel> InitCity()
        {
            List<CityModel> listCM = new List<CityModel>();
            DataAccess da = new DataAccess(sqlXmlFileName,true);

            try
            {
                DataTable dt = da.RunQuery("InitCity");
                if (dt.Rows.Count > 0)
                {
                    listCM = (from p in dt.Select()
                              select new CityModel
                              {
                                  intCityCode = Int32.Parse(p["intCityCode"].ToString()),
                                  strCity = p["strCity"].ToString()
                              }).ToList();

                    return listCM;
                } // If has data
            } // Try run query: InitCity
            catch (Exception e)
            {
                logger.Error("InitCity " + e.Message);  // Error log
            } // Catch exception: all

            return default(List<CityModel>);
        } // List<CityModel> InitCity()




        /// <summary>
        /// 以被選擇的intCityCode產生對應的鄉鎮市區列表
        /// </summary>
        /// <param name="intCityCode">城市代碼</param>
        /// <returns>鄉鎮市區列表</returns>
        public static List<AreaModel> GetAreasByCityCode(int intCityCode)
        {
            List<AreaModel> listAM = new List<AreaModel>();
            DataAccess da = new DataAccess(sqlXmlFileName, true);
            List<SqlParameter> param = new List<SqlParameter>();
            param.Add(new SqlParameter("@intCityCode", intCityCode));

            try
            {
                DataTable dt = da.RunQuery("GetAreasByCityCode", param.ToArray());
                if (dt.Rows.Count > 0)
                {
                    listAM = (from p in dt.Select()
                              select new AreaModel
                              {
                                  intZipCode = Int32.Parse(p["intZipCode"].ToString()),
                                  strArea = p["strArea"].ToString()
                              }).ToList();
                    return listAM;
                } // If has data
            } // Try run query: GetAreasByCityCode
            catch (Exception e)
            {
                logger.Error("GetAreasByCityCode " + e.Message);  // Error log
            } // Catch exception: all

            return default(List<AreaModel>);
        } // List<AreaModel> GetArea(intCityCode)




        /// <summary>
        /// 以郵遞區號獲得城市代碼
        /// </summary>
        public static int GetCityCodeByZipCode(int intZipCode)
        {
            int CityCode = 0;

            CityModel obj = new CityModel();
            DataAccess da = new DataAccess(sqlXmlFileName, true);
            List<SqlParameter> param = new List<SqlParameter>();
            param.Add(new SqlParameter("@intZipCode", intZipCode));

            try
            {
                DataTable dt = da.RunQuery("GetCityCodeByZipCode", param.ToArray());
                if (dt.Rows.Count > 0)
                {
                    obj = (from p in dt.Select()
                           select new CityModel
                           {
                               intCityCode = Int32.Parse(p["intCityCode"].ToString()),
                               strCity = p["strCity"].ToString()
                           }).First();
                    CityCode = obj.intCityCode;
                } // If has data
            } // Try run query: GetAreasByCityCode
            catch (Exception e)
            {
                logger.Error("GetCityCodeByZipCode " + e.Message);  // Error log
            } // Catch exception: all

            return CityCode;
        } //CityCodeByZipCode()








        


    }
}

CommonMoudle/Areas/CitySelect/Models/CitySelectModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CommonMoudle.Areas.CitySelect.Models
{
    public class CityModel
    {
        /// <summary>
        /// 城市代碼
        /// </summary>
        public int intCityCode { get; set; }

        /// <summary>
        /// 城市名稱
        /// </summary>
        public String strCity { get; set; }
    } // Model: City

    public class AreaModel
    {
        /// <summary>
        /// 區代碼(郵遞區號)
        /// </summary>
        public int intZipCode { get; set; }

        /// <summary>
        /// 區名稱
        /// </summary>
        public String strArea { get; set; }
    } // Model: Area

}

CommonMoudle/Areas/CitySelect/Controllers/CitySelectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommonMoudle.Areas.CitySelect.Models;

namespace CommonMoudle.Areas.CitySelect.Controllers
{
    public class CitySelectController : Controller
    {

        /// <summary>
        /// 說明頁
        /// </summary>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 城市下拉選單
        /// </summary>
        public ActionResult CitySelect()
        {           
            return View();
        }


        /// <summary>
        /// 取得城市清單
        /// </summary>
        public ActionResult CityList()
        {
            List<CityModel> ListCityModel = new List<CityModel>();
            ListCityModel = CitySelectHelper.InitCity();
            return View(ListCityModel);
        }

        /// <summary>
        /// 取得對應所選城市的區域清單
        /// </summary>
        public ActionResult AreaList(int intCityCode)
        {
            List<AreaModel> ListAreaModel = new List<AreaModel>();
            ListAreaModel = CitySelectHelper.GetAreasByCityCode(intCityCode);

            return View(ListAreaModel);
        }


    }
}

CommonMoudle/Areas/CitySelect/Views/CitySelect/AreaList.cshtml
@model List<CommonMoudle.Areas.CitySelect.Models.AreaModel>
@{
    Layout = null;
}

<option value="0">鄉鎮市區</option>
@if ( Model != null )
{
    foreach (var areaItem in Model)
    {
        <option value="@areaItem.intZipCode">@areaItem.strArea (@areaItem.intZipCode)</option>
    } // foreach
}

CommonMoudle/Areas/CitySelect/Views/CitySelect/CityList.cshtml
@model List<CommonMoudle.Areas.CitySelect.Models.CityModel>
@{
    Layout = null;
}

<option value="0">縣市</option>
@if (Model != null)
{
    foreach (var cityItem in Model)
    {
        <option value="@cityItem.intCityCode">@cityItem.strCity</option>
    } // foreach
}

CommonMoudle/Areas/CitySelect/Views/CitySelect/CitySelect.cshtml
 @Scripts.Render("~/bundles/jquery")

<select id="strCity" name="strCity" onchange="fCityChange($(this));">@Html.Action("CityList", "CitySelect", new { area = "CitySelect" })
</select>
<select id="intZipCode" name="intZipCode">@Html.Action("AreaList", "CitySelect", new { area = "CitySelect", intCityCode = 0 })
</select>

<script type="text/javascript">
    function fCityChange(varCityObj) {

        var varIntCityCode = varCityObj.val();

        $.ajax({
            url: '@Url.Action("AreaList", "CitySelect", new { area = "CitySelect" })',
            data: { intCityCode: varIntCityCode },
            type: "POST",
            async: true,
            cache: true,
            success: function (list) {
                $('#intZipCode option').remove();
                $('#intZipCode').append(list);

            }
        });
    } // fCityChange()

</script>

CommonMoudle/Areas/CitySelect/Views/CitySelect/Index.cshtml
<pre>
【模組名稱】
城市、鄉鎮市區連動下拉選單

【功能】
1.產生城市、鄉鎮市區連動下拉選單
2.利用郵遞區號回推城市代碼


【建置方法】
將本Area加入專案


【使用方法】
將以下內容加入需要選單的View中:
Html下拉選單初始化=&gt;

  
 &lt;select id="strCity" name="strCity" onchange="fCityChange($(this));"&gt; Html.Action("CityList", "CitySelect", new { area = "CitySelect" })
 &lt;/select&gt;
 &lt;select id="intZipCode" name="intZipCode"&gt; Html.Action("AreaList", "CitySelect", new { area = "CitySelect", intCityCode = 0 })
 &lt;/select&gt;
 

javascript部分，選擇城市後改變區域選單內容=&gt;
 &lt;script type="text/javascript"&gt;
    function fCityChange(varCityObj) {
       

        var varIntCityCode = varCityObj.val();

        $.ajax({
            url: '@Url.Action("AreaList", "CitySelect", new { area = "CitySelect" })',
            data: { intCityCode: varIntCityCode },
            type: "POST",
            async: true,
            cache: true,
            success: function (list) {
                $('#intZipCode option').remove();
                $('#intZipCode').append(list);

            }
        });
    } // fCityChange()

 &lt;/script&gt;

若需以郵遞區號獲得城市代碼
叫用GetCityCodeByZipCode(郵遞區號)
</pre>